version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: solidev-backend:latest
    container_name: solidev-backend
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - BIND=0.0.0.0
      # Si deseas forzar puertos sin depender de interpolación:
      # - HTTP_PORT=3002
    ports:
      - "${HTTP_PORT:-3002}:${HTTP_PORT:-3002}"
    volumes:
      # Monta certificados en solo lectura; las rutas coinciden con SSL_* del .env
      - ./key.pem:/app/key.pem:ro
      - ./cert.pem:/app/cert.pem:ro
    restart: always